[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
extend-select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.lint.isort]
force-single-line = false

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.flake8]
max-line-length = 100
exclude = [
    "venv",
    ".venv",
    ".git",
    "__pycache__",
    "migrations",
    "alembic",
    "build",
    "dist"
]
per-file-ignores = [
    "tests/*:E501,F401,F841,F541,E402,E722,E712,F821",
    "alembic/*:E402,F403,F401"
]
ignore = [
    "E203",  # whitespace before ':'
    "W503",  # line break before binary operator
    "E501",  # line too long (handled by black)
    "F401",  # unused imports (handled by autoflake)
    "F841",  # unused variables (handled by autoflake)
    "F541",  # f-string without placeholders
    "E402",  # module level import not at top
    "E722",  # bare except
    "E712",  # comparison to True/False
    "F821",  # undefined name
    "F811",  # redefinition of unused
    "F403",  # star import
    "E231"   # missing whitespace
]
