[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 100
exclude = [
    "venv",
    ".venv",
    ".git",
    "__pycache__",
    "migrations",
    "alembic",
    "build",
    "dist"
]
per-file-ignores = [
    "tests/*:E501,F401,F841,F541,E402,E722,E712,F821",
    "alembic/*:E402,F403,F401"
]
ignore = [
    "E203",  # whitespace before ':'
    "W503",  # line break before binary operator
    "E501",  # line too long (handled by black)
    "F401",  # unused imports (handled by autoflake)
    "F841",  # unused variables (handled by autoflake)
    "F541",  # f-string without placeholders
    "E402",  # module level import not at top
    "E722",  # bare except
    "E712",  # comparison to True/False
    "F821",  # undefined name
    "F811",  # redefinition of unused
    "F403",  # star import
    "E231"   # missing whitespace
]
