# Prometheus alert rules for ACP services
groups:
  - name: acp_service_alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(acp_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for service {{ $labels.service }}"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(acp_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }}s for service {{ $labels.service }}"

      # Resource usage alerts
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% for service {{ $labels.job }}"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}MB for service {{ $labels.job }}"

      # Database alerts
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database has {{ $value }} active connections"

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database slow queries detected"
          description: "Database query efficiency is low: {{ $value }}"

      # Queue alerts
      - alert: HighQueueSize
        expr: acp_queue_size > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High queue size"
          description: "Queue {{ $labels.queue_name }} has {{ $value }} items"

      - alert: QueueProcessingStalled
        expr: rate(acp_ingestion_total[5m]) == 0 and acp_queue_size > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Queue processing stalled"
          description: "No items processed from queue {{ $labels.queue_name }} for 5 minutes"

      # Vector database alerts
      - alert: VectorOperationErrors
        expr: rate(acp_vector_operations_total{status="error"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Vector operation errors"
          description: "Vector operation error rate is {{ $value }} for {{ $labels.operation }}"

      # Security alerts
      - alert: HighFailedAuthAttempts
        expr: rate(acp_requests_total{endpoint="/auth/login", status_code="401"}[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High failed authentication attempts"
          description: "Failed auth rate is {{ $value }} attempts per second"

      - alert: RateLimitExceeded
        expr: rate(acp_requests_total{status_code="429"}[5m]) > 0.05
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times per second"

  - name: infrastructure_alerts
    rules:
      # Disk space alerts
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% full on {{ $labels.instance }}"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk space"
          description: "Disk space is {{ $value }}% full on {{ $labels.instance }}"

      # System load alerts
      - alert: HighSystemLoad
        expr: node_load1 > 4
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system load"
          description: "System load is {{ $value }} on {{ $labels.instance }}"

      # Redis alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} is down"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}% on {{ $labels.instance }}"

      # Network alerts
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000  # 100MB/s
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "High network traffic"
          description: "Network receive rate is {{ $value }} bytes/s on {{ $labels.instance }}"

